# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up  pre-commit cloudformation-cli cloudformation-cli-java-plugin
        run: pip install pre-commit cloudformation-cli cloudformation-cli-java-plugin
      - name: install and run pre-commit for all files
        run: pre-commit run --all-files
      - name: Verify AWS::MemoryDB::ACL
        run: |
          cd "${GITHUB_WORKSPACE}/aws-memorydb-acl"
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify
      - name: Verify AWS::MemoryDB::Cluster
        run: |
          cd "${GITHUB_WORKSPACE}/aws-memorydb-cluster"
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify
      - name: Verify AWS::MemoryDB::ParameterGroup
        run: |
          cd "${GITHUB_WORKSPACE}/aws-memorydb-parametergroup"
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify
      - name: Verify AWS::MemoryDB::SubnetGroup
        run: |
          cd "${GITHUB_WORKSPACE}/aws-memorydb-subnetgroup"
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify
      - name: Verify AWS::MemoryDB::User
        run: |
          cd "${GITHUB_WORKSPACE}/aws-memorydb-user"
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify
